[build]
  command = "npm run build"
  publish = "out"

# Ensure correct MIME for .wasm
[[headers]]
  for = "/ifc/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"
